export type NllbLanguage = {
  code: string;
  name: string;
  speechLocale?: string;
};

// Full NLLB-200 language list (distilled-600M supported codes)
export const NLLB_LANGUAGES: NllbLanguage[] = [
  { code: "ace_Arab", name: "Acehnese (Arabic script)" },
  { code: "ace_Latn", name: "Acehnese (Latin script)" },
  { code: "acm_Arab", name: "Mesopotamian Arabic" },
  { code: "acq_Arab", name: "Ta'izzi-Adeni Arabic" },
  { code: "aeb_Arab", name: "Tunisian Arabic" },
  { code: "afr_Latn", name: "Afrikaans" },
  { code: "ajp_Arab", name: "South Levantine Arabic" },
  { code: "aka_Latn", name: "Akan" },
  { code: "amh_Ethi", name: "Amharic" },
  { code: "apc_Arab", name: "North Levantine Arabic" },
  { code: "arb_Arab", name: "Arabic", speechLocale: "ar-SA" },
  { code: "ars_Arab", name: "Najdi Arabic" },
  { code: "ary_Arab", name: "Moroccan Arabic" },
  { code: "arz_Arab", name: "Egyptian Arabic" },
  { code: "asm_Beng", name: "Assamese" },
  { code: "ast_Latn", name: "Asturian" },
  { code: "awa_Deva", name: "Awadhi" },
  { code: "ayr_Latn", name: "Central Aymara" },
  { code: "azb_Arab", name: "South Azerbaijani" },
  { code: "azj_Latn", name: "North Azerbaijani" },
  { code: "bak_Cyrl", name: "Bashkir" },
  { code: "bam_Latn", name: "Bambara" },
  { code: "ban_Latn", name: "Balinese" },
  { code: "bel_Cyrl", name: "Belarusian" },
  { code: "bem_Latn", name: "Bemba" },
  { code: "ben_Beng", name: "Bengali" },
  { code: "bho_Deva", name: "Bhojpuri" },
  { code: "bjn_Arab", name: "Banjar (Arabic script)" },
  { code: "bjn_Latn", name: "Banjar (Latin script)" },
  { code: "bod_Tibt", name: "Standard Tibetan" },
  { code: "bos_Latn", name: "Bosnian" },
  { code: "bug_Latn", name: "Buginese" },
  { code: "bul_Cyrl", name: "Bulgarian" },
  { code: "cat_Latn", name: "Catalan", speechLocale: "ca-ES" },
  { code: "ceb_Latn", name: "Cebuano" },
  { code: "ces_Latn", name: "Czech", speechLocale: "cs-CZ" },
  { code: "cjk_Latn", name: "Chokwe" },
  { code: "ckb_Arab", name: "Central Kurdish" },
  { code: "crh_Latn", name: "Crimean Tatar" },
  { code: "cym_Latn", name: "Welsh" },
  { code: "dan_Latn", name: "Danish", speechLocale: "da-DK" },
  { code: "deu_Latn", name: "German", speechLocale: "de-DE" },
  { code: "dik_Latn", name: "Southwestern Dinka" },
  { code: "dyu_Latn", name: "Dyula" },
  { code: "dzo_Tibt", name: "Dzongkha" },
  { code: "ell_Grek", name: "Greek", speechLocale: "el-GR" },
  { code: "eng_Latn", name: "English", speechLocale: "en-US" },
  { code: "epo_Latn", name: "Esperanto" },
  { code: "est_Latn", name: "Estonian", speechLocale: "et-EE" },
  { code: "eus_Latn", name: "Basque" },
  { code: "ewe_Latn", name: "Ewe" },
  { code: "fao_Latn", name: "Faroese" },
  { code: "fij_Latn", name: "Fijian" },
  { code: "fin_Latn", name: "Finnish", speechLocale: "fi-FI" },
  { code: "fon_Latn", name: "Fon" },
  { code: "fra_Latn", name: "French", speechLocale: "fr-FR" },
  { code: "fur_Latn", name: "Friulian" },
  { code: "fuv_Latn", name: "Nigerian Fulfulde" },
  { code: "gla_Latn", name: "Scottish Gaelic" },
  { code: "gle_Latn", name: "Irish" },
  { code: "glg_Latn", name: "Galician" },
  { code: "grn_Latn", name: "Guarani" },
  { code: "guj_Gujr", name: "Gujarati" },
  { code: "hat_Latn", name: "Haitian Creole" },
  { code: "hau_Latn", name: "Hausa" },
  { code: "heb_Hebr", name: "Hebrew", speechLocale: "he-IL" },
  { code: "hin_Deva", name: "Hindi", speechLocale: "hi-IN" },
  { code: "hne_Deva", name: "Chhattisgarhi" },
  { code: "hrv_Latn", name: "Croatian", speechLocale: "hr-HR" },
  { code: "hun_Latn", name: "Hungarian", speechLocale: "hu-HU" },
  { code: "hye_Armn", name: "Armenian" },
  { code: "ibo_Latn", name: "Igbo" },
  { code: "ilo_Latn", name: "Ilocano" },
  { code: "ind_Latn", name: "Indonesian", speechLocale: "id-ID" },
  { code: "isl_Latn", name: "Icelandic" },
  { code: "ita_Latn", name: "Italian", speechLocale: "it-IT" },
  { code: "jav_Latn", name: "Javanese" },
  { code: "jpn_Jpan", name: "Japanese", speechLocale: "ja-JP" },
  { code: "kab_Latn", name: "Kabyle" },
  { code: "kac_Latn", name: "Jingpho" },
  { code: "kam_Latn", name: "Kamba" },
  { code: "kan_Knda", name: "Kannada" },
  { code: "kas_Arab", name: "Kashmiri (Arabic script)" },
  { code: "kas_Deva", name: "Kashmiri (Devanagari script)" },
  { code: "kat_Geor", name: "Georgian" },
  { code: "knc_Arab", name: "Central Kanuri (Arabic script)" },
  { code: "knc_Latn", name: "Central Kanuri (Latin script)" },
  { code: "kaz_Cyrl", name: "Kazakh" },
  { code: "kbp_Latn", name: "Kabiyè" },
  { code: "kea_Latn", name: "Kabuverdianu" },
  { code: "khm_Khmr", name: "Khmer" },
  { code: "kik_Latn", name: "Kikuyu" },
  { code: "kin_Latn", name: "Kinyarwanda" },
  { code: "kir_Cyrl", name: "Kyrgyz" },
  { code: "kln_Latn", name: "Kalaallisut" },
  { code: "kom_Cyrl", name: "Komi" },
  { code: "kon_Latn", name: "Kikongo" },
  { code: "kor_Hang", name: "Korean", speechLocale: "ko-KR" },
  { code: "lao_Laoo", name: "Lao" },
  { code: "lij_Latn", name: "Ligurian" },
  { code: "lim_Latn", name: "Limburgish" },
  { code: "lin_Latn", name: "Lingala" },
  { code: "lit_Latn", name: "Lithuanian", speechLocale: "lt-LT" },
  { code: "lmo_Latn", name: "Lombard" },
  { code: "ltg_Latn", name: "Latgalian" },
  { code: "ltz_Latn", name: "Luxembourgish" },
  { code: "lua_Latn", name: "Luba-Kasai" },
  { code: "lug_Latn", name: "Ganda" },
  { code: "luo_Latn", name: "Luo" },
  { code: "lus_Latn", name: "Mizo" },
  { code: "lvs_Latn", name: "Standard Latvian", speechLocale: "lv-LV" },
  { code: "mag_Deva", name: "Magahi" },
  { code: "mai_Deva", name: "Maithili" },
  { code: "mal_Mlym", name: "Malayalam" },
  { code: "mar_Deva", name: "Marathi" },
  { code: "min_Arab", name: "Minangkabau (Arabic script)" },
  { code: "min_Latn", name: "Minangkabau (Latin script)" },
  { code: "mkd_Cyrl", name: "Macedonian" },
  { code: "plt_Latn", name: "Plateau Malagasy" },
  { code: "mlt_Latn", name: "Maltese" },
  { code: "mni_Beng", name: "Meitei (Bengali script)" },
  { code: "khk_Cyrl", name: "Halh Mongolian" },
  { code: "mos_Latn", name: "Mossi" },
  { code: "mri_Latn", name: "Maori" },
  { code: "mya_Mymr", name: "Burmese" },
  { code: "nld_Latn", name: "Dutch", speechLocale: "nl-NL" },
  { code: "nno_Latn", name: "Norwegian Nynorsk" },
  { code: "nob_Latn", name: "Norwegian Bokmål", speechLocale: "nb-NO" },
  { code: "npi_Deva", name: "Nepali" },
  { code: "nso_Latn", name: "Northern Sotho" },
  { code: "nus_Latn", name: "Nuer" },
  { code: "nya_Latn", name: "Nyanja" },
  { code: "oci_Latn", name: "Occitan" },
  { code: "gaz_Latn", name: "West Central Oromo" },
  { code: "ory_Orya", name: "Odia" },
  { code: "pag_Latn", name: "Pangasinan" },
  { code: "pan_Guru", name: "Eastern Panjabi" },
  { code: "pap_Latn", name: "Papiamento" },
  { code: "pes_Arab", name: "Western Persian", speechLocale: "fa-IR" },
  { code: "pol_Latn", name: "Polish", speechLocale: "pl-PL" },
  { code: "por_Latn", name: "Portuguese", speechLocale: "pt-PT" },
  { code: "prs_Arab", name: "Dari" },
  { code: "pbt_Arab", name: "Southern Pashto" },
  { code: "quy_Latn", name: "Ayacucho Quechua" },
  { code: "ron_Latn", name: "Romanian", speechLocale: "ro-RO" },
  { code: "run_Latn", name: "Rundi" },
  { code: "rus_Cyrl", name: "Russian", speechLocale: "ru-RU" },
  { code: "sag_Latn", name: "Sango" },
  { code: "san_Deva", name: "Sanskrit" },
  { code: "sat_Olck", name: "Santali" },
  { code: "scn_Latn", name: "Sicilian" },
  { code: "shn_Mymr", name: "Shan" },
  { code: "sin_Sinh", name: "Sinhala" },
  { code: "slk_Latn", name: "Slovak", speechLocale: "sk-SK" },
  { code: "slv_Latn", name: "Slovenian" },
  { code: "smo_Latn", name: "Samoan" },
  { code: "sna_Latn", name: "Shona" },
  { code: "snd_Arab", name: "Sindhi" },
  { code: "som_Latn", name: "Somali" },
  { code: "sot_Latn", name: "Southern Sotho" },
  { code: "spa_Latn", name: "Spanish", speechLocale: "es-ES" },
  { code: "als_Latn", name: "Tosk Albanian" },
  { code: "srd_Latn", name: "Sardinian" },
  { code: "srp_Cyrl", name: "Serbian" },
  { code: "ssw_Latn", name: "Swati" },
  { code: "sun_Latn", name: "Sundanese" },
  { code: "swe_Latn", name: "Swedish", speechLocale: "sv-SE" },
  { code: "swh_Latn", name: "Swahili", speechLocale: "sw-KE" },
  { code: "szl_Latn", name: "Silesian" },
  { code: "tam_Taml", name: "Tamil" },
  { code: "tat_Cyrl", name: "Tatar" },
  { code: "tel_Telu", name: "Telugu" },
  { code: "tgk_Cyrl", name: "Tajik" },
  { code: "tgl_Latn", name: "Tagalog", speechLocale: "fil-PH" },
  { code: "tha_Thai", name: "Thai", speechLocale: "th-TH" },
  { code: "tir_Ethi", name: "Tigrinya" },
  { code: "taq_Latn", name: "Tamasheq (Latin script)" },
  { code: "taq_Tfng", name: "Tamasheq (Tifinagh script)" },
  { code: "tpi_Latn", name: "Tok Pisin" },
  { code: "tsn_Latn", name: "Tswana" },
  { code: "tso_Latn", name: "Tsonga" },
  { code: "tuk_Latn", name: "Turkmen" },
  { code: "tum_Latn", name: "Tumbuka" },
  { code: "tur_Latn", name: "Turkish", speechLocale: "tr-TR" },
  { code: "twi_Latn", name: "Twi" },
  { code: "tzm_Tfng", name: "Central Atlas Tamazight" },
  { code: "uig_Arab", name: "Uyghur" },
  { code: "ukr_Cyrl", name: "Ukrainian", speechLocale: "uk-UA" },
  { code: "umb_Latn", name: "Umbundu" },
  { code: "urd_Arab", name: "Urdu", speechLocale: "ur-PK" },
  { code: "uzn_Latn", name: "Northern Uzbek" },
  { code: "vec_Latn", name: "Venetian" },
  { code: "vie_Latn", name: "Vietnamese", speechLocale: "vi-VN" },
  { code: "war_Latn", name: "Waray" },
  { code: "wol_Latn", name: "Wolof" },
  { code: "xho_Latn", name: "Xhosa" },
  { code: "ydd_Hebr", name: "Eastern Yiddish" },
  { code: "yor_Latn", name: "Yoruba" },
  { code: "yue_Hant", name: "Yue Chinese" },
  { code: "zho_Hans", name: "Chinese (Simplified)", speechLocale: "zh-CN" },
  { code: "zho_Hant", name: "Chinese (Traditional)", speechLocale: "zh-TW" },
  { code: "zsm_Latn", name: "Standard Malay", speechLocale: "ms-MY" },
  { code: "zul_Latn", name: "Zulu" },
];

export const NLLB_LANGUAGES_BY_CODE = new Map(NLLB_LANGUAGES.map((l) => [l.code, l]));

// Default 7 languages shown in the main page Select
export const DEFAULT_LANGUAGE_CODES = [
  "rus_Cyrl",
  "eng_Latn",
  "spa_Latn",
  "fra_Latn",
  "hin_Deva",
  "zho_Hans",
  "arb_Arab",
] as const;

export function getNllbSpeechLocale(code: string): string {
  return NLLB_LANGUAGES_BY_CODE.get(code)?.speechLocale ?? "en-US";
}

// Extracts ISO 639-3 from NLLB code (e.g. "quy_Latn" → "quy")
function nllbToIso(code: string): string {
  return code.split("_")[0];
}

// Cache per locale to avoid recreating Intl.DisplayNames on every keystroke
const displayNamesCache = new Map<string, Intl.DisplayNames>();

function getDisplayNames(uiLocale: string): Intl.DisplayNames {
  const cached = displayNamesCache.get(uiLocale);
  if (cached) return cached;
  const dn = new Intl.DisplayNames([uiLocale, "en"], { type: "language", fallback: "none" });
  displayNamesCache.set(uiLocale, dn);
  return dn;
}

export function getLocalizedLanguageName(nllbCode: string, uiLocale: string): string {
  try {
    const localized = getDisplayNames(uiLocale).of(nllbToIso(nllbCode));
    if (localized) return localized;
  } catch {
    // Intl not available or code not recognised
  }
  return NLLB_LANGUAGES_BY_CODE.get(nllbCode)?.name ?? nllbCode;
}
